name: build

on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  core:
    name: ğŸ¤– core
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘‡ Checkout
        uses: actions/checkout@v2

      - name: ğŸ“¦ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: ğŸ“¦ Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: âœğŸ¼ Version
        id: version
        uses: endaft/action-yamler@v1.0.6
        with:
          file: ./pubspec.yaml
          path: version
          set: ${{ format('-dev.{0}', github.run_number) }}
          get: true
          append: true

      - name: ğŸ‘· Make
        run: make

      - name: ğŸ· Tags
        uses: endaft/action-dev-tagger@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: ${{ format('{0}-dev.', steps.version.outputs.value_old) }}
          tag: ${{ format('{0}-dev.{1}', steps.version.outputs.value_old, github.run_number) }}

      - name: âœğŸ¼ Changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/tag-changelog-config.js

      - name: âœğŸ¼ Prepend Changelog
        uses: endaft/action-prepend@v0.0.4
        with:
          file_target: ./CHANGELOG.md
          value_in: ${{ steps.changelog.outputs.changelog }}
          is_file: "false"

      - name: ğŸš€ publish dev
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
